name: pipenv-update
on:
  schedule:
    - cron:  '8 22 * * 1'
  workflow_dispatch:

jobs:
  pipenv-update:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pipenv update
          git add -u
          git commit -m "update pipenv packages"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: bump checkov pypi packages version
          committer: GitHub <action@github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: '[AUTO-PR] Update pipenv packages'
          body: |
            bump pipenv packages
            - Auto-generated by [pipenv-update github action](.github/workflows/pipenv-update.yml)
          labels: automated pr
          branch: pipenvfix
          branch-suffix: timestamp
