name: RegressionTests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - add_regression_test

jobs:
  PrismaTest:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: dschep/install-pipenv-action@v1
      - name: Clone Terragoat - vulnerable terraform
        run: git clone https://github.com/bridgecrewio/terragoat
      - name: Build & install checkov package
        run: |
          pipenv --python ${{ matrix.python }}
          pipenv run pip install --upgrade pip==21.1.1
          pipenv run pip install pytest
          pipenv run python setup.py sdist bdist_wheel
          pipenv run pip install dist/checkov-*.whl
      - name: Run checkov with Primsa creds
        env:
          PRISMA_KEY: ${{ secrets.PRISMA_KEY }}
          PRISMA_API_URL: ${{ secrets.PRISMA_API_URL }}
        run: |
          pipenv run checkov -s -d terragoat --bc-api-key $PRISMA_KEY --repo-id yuvalyacoby/terragoat > checkov_report_prisma.txt
          grep "prismacloud.io" checkov_report_prisma.txt
          exit $?
